### PR TITLE
Make SvgChart and Axes public.

### PR DESCRIPTION
**Pull request by martinfrances107**
This is related to this issue #11

### CODE REVIEW

**Comment by LangPham** [comment]
In my opinion, when creating this library, I thought about user interaction with the chart. That's why I use leptos.
- So in the theta plot I use 3d coordinates, I hold the Z axis to zoom later.
- The axes take some calculations to create the bars, it requires data to create better looking axes. Later when the zoom feature is implemented, it will need to be recalculated.
- SvgChart is just a simple svg tag

If you just need to add the title, you can wrap it in another svg tag:
```rust
#[component]
pub fn App() -> impl IntoView {
    let chart = Cartesian::new(
        Series::from(vec![50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150]).set_range(40., 160.),
        Series::from(vec![7, 8, 8, 9, 9, 9, 10, 11, 14, 14, 15]).set_range(6., 16.),
    )
    .set_view(820, 620, 3, 100, 100, 20);

    view! {
        <svg class="chart" viewBox="0 0 820 620">
            <text x="150" y="50">"Custom Title"</text>
            <ScatterChart chart=chart />
        </svg>
    }
}
```

**Comment by martinfrances107** [comment]
I think my example, was a bad talking point

I was going for the smallest change that demonstrated that the "SvgChart" feature was connected and working 

By custom graph, what I want to just use SvgChart as a shell. Inside the shell I want to put custom code .. In the real world I want to put a Voronoi and Delaunay diagram from a crate I have been working on [d3_delaunay](https://crates.io/crates/d3_delaunay_rs)

Over the weekend .. I will try and come up with a more complex demonstration of why custom graphs are useful.

500_points

**Comment by LangPham** [comment]
It looks interesting, I'll try to learn about it

**Comment by martinfrances107** [comment]
So the example takes the same set of points the the scatter_chart example.

and displays the delaunay triangulation.

**Comment by LangPham** [comment]
Hello @martinfrances107,

I have an example of delaunay https://github.com/theta-vn/leptos_chart/tree/feature/delaunator.

You can drag it and https://github.com/theta-vn/theta-chart/tree/feature/delaunator in the same folder to test.

I will add Voronoi later.

**Comment by martinfrances107** [comment]
When I check out the detonator branch I could not get examples/delaunay to work..

I appreciate as a library, the aim is to serve the needs of many different groups of users 
A library cannot serve the needs each individual user. 

A) I want to custom graph to add a threshold line to a scatter graph
B)  I want to add a text the label to one point inside the delaunay mesh

Thank you for listening but I think that means I should folk this project, and produce my own custom charts.

**Comment by LangPham** [comment]
I have added Voronoi Diagram in version 0.2.2
You can refer to it and give me suggestions!

**Comment by martinfrances107** [comment]
I will take a look and give a review and help out where I can.

**Pull request closed without merging**
